import { Args, Flags } from '@oclif/core';
import VegaCommand, { VegaCommandOptions, selectWalletFlags } from '../../lib/vega-command.js';
import {
  getNativeBCHTokenInfo, bigIntToDecString, binToHex, bigIntFromDecString,
  moriaTxResultSummaryJSON, convertUTXOToJSON,
} from '../../lib/util.js';
import { ValueError } from '../../lib/exceptions.js';
import { MUSDV0_SYMBOL, MUSDV0_DECIMALS } from '../../lib/constants.js';
import type { UTXOWithNFT } from '@cashlab/common';
import { uint8ArrayEqual, hexToBin } from '@cashlab/common/util.js';

export default class Moria0AddCollateral extends VegaCommand<typeof Moria0AddCollateral> {
  static args = {
    loan_outpoint: Args.string({
      name: 'loan_outpoint',
      required: true,
      description: "The outpoint of the loan nft utxo. <txid>:<index>",
    }),
    additional_amount: Args.string({
      name: 'additional_amount',
      required: true,
      description: "Increase the loan's collateral by the additional_amount. The amount is a decimal number, 1.00000000 is equal to 100000000 sats or one bch.",
    }),
  };
  static flags = {
    ...selectWalletFlags(),
    'txfee-per-byte': Flags.string({
      description: 'Specify the txfee per byte in sats.',
      required: true,
      default: '1',
    }),
    'broadcast': Flags.boolean({
      description: `Broadcast the transactions generated by the command.`,
    }),
  };
  static vega_options: VegaCommandOptions = {
    require_wallet_selection: true,
  };

  static description = ``;

  static examples = [
    `<%= config.bin %> <%= command.id %>`,
  ];

  async run (): Promise<any> {
    const { args, flags } = this;
    const bch_token_info = getNativeBCHTokenInfo();
    const wallet_name = this.getSelectedWalletName();
    const { default: MoriaV0 } = await import('@cashlab/moria/v0/index.js');
    const loans: UTXOWithNFT[] = await this.callModuleMethod('moria0.get-loans');
    let selected_loan_outpoint;
    {
      const [ outpoint_txid, outpoint_index ] = args.loan_outpoint.split(':');
      if (typeof outpoint_index != 'string' || isNaN(parseInt(outpoint_index)) && parseInt(outpoint_index) > 0) {
        throw new ValueError(`loan_outpoint index is not a positive number!`);
      }
      const outpoint_txhash = hexToBin(outpoint_txid as string);
      if (outpoint_txhash.length != 32) {
        throw new ValueError(`loan_outpoint txhash should be a 32 bytes represented in hexstring!`);
      }
      selected_loan_outpoint = { txhash: outpoint_txhash, index: parseInt(outpoint_index) };
    }
    const selected_loan: UTXOWithNFT | undefined = loans.find((a) => uint8ArrayEqual(a.outpoint.txhash, selected_loan_outpoint.txhash) && a.outpoint.index == selected_loan_outpoint.index);
    if (selected_loan == null) {
      throw new ValueError(`Provided loan_outpoint not found in the wallet's loans.`);
    }
    const additional_amount = bigIntFromDecString(args.additional_amount, bch_token_info.decimals);
    if (!(additional_amount > 0n)) {
      throw new ValueError(`additional_amount should be greater than zero.`);
    }
    const broadcast = flags.broadcast;
    const txfee_per_byte: bigint = BigInt(flags['txfee-per-byte']);
    if (txfee_per_byte < 0n) {
      throw new Error('txfee-per-byte should be a positive integer');
    }
    const result = await this.callModuleMethod('moria0.loan-add-collateral', wallet_name, selected_loan, additional_amount, { broadcast, txfee_per_byte, verify: true });
    this.log('Summary:');
    try {
      const loan_params = MoriaV0.parseParametersFromLoanNFTCommitment(result.loan_utxo.output.token.nft.commitment);
      this.log(`  Loan amount: ${bigIntToDecString(loan_params.amount, MUSDV0_DECIMALS)} ${MUSDV0_SYMBOL}`);
      this.log(`  Collateral amount: ${bigIntToDecString(result.loan_utxo.output.amount, bch_token_info.decimals)} ${bch_token_info.symbol}`);
      this.log(`  Transaction fee: ${result.txfee} sats`);
    } catch (err) {
      this.log(`  Parse error: [${(err as any).name}] ${(err as any).message}`);
    }
    return {
      ...moriaTxResultSummaryJSON(result)
    };
  }
}
