import { Args, Flags } from '@oclif/core';
import VegaCommand, { VegaCommandOptions, selectWalletFlags } from '../../lib/vega-command.js';
import {
  getNativeBCHTokenInfo, bigIntToDecString, binToHex, bigIntFromDecString,
  moriaTxResultSummaryJSON, convertUTXOToJSON,
} from '../../lib/util.js';
import { ValueError } from '../../lib/exceptions.js';
import { MUSDV0_SYMBOL, MUSDV0_DECIMALS } from '../../lib/constants.js';
import type { UTXOWithNFT } from '@cashlab/common';
import { uint8ArrayEqual, hexToBin } from '@cashlab/common/util.js';

export default class Moria0LiquidateLoan extends VegaCommand<typeof Moria0LiquidateLoan> {
  static args = {
    loan_outpoint: Args.string({
      name: 'loan_outpoint',
      required: true,
      description: "The outpoint of the loan nft utxo. <txid>:<index>",
    }),
  };
  static flags = {
    ...selectWalletFlags(),
    'txfee-per-byte': Flags.string({
      description: 'Specify the txfee per byte in sats.',
      required: true,
      default: '1',
    }),
    'broadcast': Flags.boolean({
      description: `Broadcast the transactions generated by the command.`,
    }),
  };
  static vega_options: VegaCommandOptions = {
    require_wallet_selection: true,
  };

  static description = ``;

  static examples = [
    `<%= config.bin %> <%= command.id %>`,
  ];

  async run (): Promise<any> {
    const { args, flags } = this;
    const bch_token_info = getNativeBCHTokenInfo();
    const wallet_name = this.getSelectedWalletName();
    const { default: MoriaV0 } = await import('@cashlab/moria/v0/index.js');
    const loans: UTXOWithNFT[] = await this.callModuleMethod('moria0.get-loans');
    let selected_loan_outpoint;
    {
      const [ outpoint_txid, outpoint_index ] = args.loan_outpoint.split(':');
      if (typeof outpoint_index != 'string' || isNaN(parseInt(outpoint_index)) && parseInt(outpoint_index) > 0) {
        throw new ValueError(`loan_outpoint index is not a positive number!`);
      }
      const outpoint_txhash = hexToBin(outpoint_txid as string);
      if (outpoint_txhash.length != 32) {
        throw new ValueError(`loan_outpoint txhash should be a 32 bytes represented in hexstring!`);
      }
      selected_loan_outpoint = { txhash: outpoint_txhash, index: parseInt(outpoint_index) };
    }
    const selected_loan: UTXOWithNFT | undefined = loans.find((a) => uint8ArrayEqual(a.outpoint.txhash, selected_loan_outpoint.txhash) && a.outpoint.index == selected_loan_outpoint.index);
    if (selected_loan == null) {
      throw new ValueError(`Provided loan_outpoint not found in the wallet's loans.`);
    }
    const broadcast = flags.broadcast;
    const txfee_per_byte: bigint = BigInt(flags['txfee-per-byte']);
    if (txfee_per_byte < 0n) {
      throw new Error('txfee-per-byte should be a positive integer');
    }
    const result = await this.callModuleMethod('moria0.liquidate-loan', wallet_name, selected_loan, { broadcast, txfee_per_byte, verify: true });
    this.log('Summary:');
    try {
      const loan_params = MoriaV0.parseParametersFromLoanNFTCommitment(selected_loan.output.token.nft.commitment);
      this.log(`  Liquidate amount: ${bigIntToDecString(loan_params.amount, MUSDV0_DECIMALS)} ${MUSDV0_SYMBOL}`);
      this.log(`  Reward: ${bigIntToDecString(selected_loan.output.amount, bch_token_info.decimals)} ${bch_token_info.symbol}`);
      this.log(`  Oracle use fee: ${result.oracle_use_fee} sats`);
      this.log(`  Transaction fee: ${result.txfee} sats`);
    } catch (err) {
      this.log(`  Parse error: [${(err as any).name}] ${(err as any).message}`);
    }
    return {
      ...moriaTxResultSummaryJSON(result),
      oracle_use_fee: result.oracle_use_fee+'',
    };
  }
}
